# Generated by Django 4.1.7 on 2023-03-10 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_alter_page_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reply_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.page'),
        ),
    ]
