# Generated by Django 4.1.7 on 2023-03-10 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_post_reply_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reply_from',
        ),
    ]
