# Generated by Django 4.1.7 on 2023-03-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0008_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, to='entities.post'),
        ),
    ]
