version: "3"

services:
  app:
    restart: always
    build: 
      context: .
      dockerfile: ./Dockerfile-core
    volumes:
      - ./:/app/
    security_opt:
      - label:type:docker_t
    entrypoint: './entrypoint-web.sh'
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - './innotter/innotter/innotter/.env'
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
