version: "3"

services:
  app:
    restart: always
    build: .
    volumes:
      - ./:/app/
    command: "poetry run python innotter/innotter/manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=myprojectuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=innotter
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
